name: Build and deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/xaazias/next-saizaax-dev
  STACK_NAME: saizaax-dev
  GH_PAT: ${{ secrets.GH_PAT }}
  GH_USER: ${{ github.actor }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to registry
        run: echo "$GH_PAT" | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin

      - name: Push image
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker tag $IMAGE_NAME $IMAGE_NAME:$GITHUB_RUN_NUMBER
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$GITHUB_RUN_NUMBER
          
  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker stack
        uses: appleboy/ssh-action@master
        env:
          REGISTRY: ${{ env.REGISTRY }}
          GH_PAT: ${{ env.GH_PAT }}
          STACK_NAME: ${{ env.STACK_NAME }}
          GH_USER: ${{ env.GH_USER }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: REGISTRY, GH_PAT, STACK_NAME, GH_USER
          script: |
            cd ~/projects/saizaax.dev
            echo "$GH_PAT" | docker login $REGISTRY -u $GH_USER --password-stdin
            docker stack deploy -c docker.stack.prod.yml $STACK_NAME --with-registry-auth
