name: Production build and Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/xaazias/next-saizaax-dev
  SERVICE_NAME: saizaaxdev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

      - name: Log in to registry
        run: echo "${{ secrets.GH_PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:latest
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:${{ github.run_number }}
  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
          SERVICE: ${{ env.SERVICE_NAME }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          envs: IMAGE, SERVICE
          script: |
            cd ~/projects/saizaax.dev
            docker-compose stop ${{ env.SERVICE }}
            docker image rm ${{ env.IMAGE }} --force
            docker-compose -f docker-compose.prod.yml up -d
